# Generated by Django 4.0.2 on 2022-03-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_categories', '0001_initial'),
        ('eshop_products', '0002_alter_product_options_alter_product_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='eshop_products_categories.ProductsCategories', verbose_name='دسته بندی ها'),
        ),
    ]
