# Generated by Django 4.0.3 on 2022-03-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=100)),
                ('site_address', models.CharField(max_length=100)),
                ('site_email', models.EmailField(max_length=254)),
                ('site_phone', models.CharField(max_length=20)),
                ('site_logo', models.ImageField(upload_to='site_logo')),
                ('site_description', models.TextField()),
                ('copyright_text', models.CharField(max_length=100)),
            ],
        ),
    ]
