# Generated by Django 4.0.3 on 2022-03-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'کل تنظیمات سایت'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_fax',
            field=models.CharField(default=656565, max_length=20, verbose_name='شماره فکس سایت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(max_length=100, verbose_name='متن حق تکثیر'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_address',
            field=models.CharField(max_length=100, verbose_name='آدرس سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_description',
            field=models.TextField(verbose_name='توضیحات سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_logo',
            field=models.ImageField(upload_to='site_logo', verbose_name='لوگوی سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_phone',
            field=models.CharField(max_length=20, verbose_name='شماره تلفن سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(max_length=100, verbose_name='عنوان سایت'),
        ),
    ]
