# Generated by Django 4.0.3 on 2022-03-05 08:49

from django.db import migrations, models
import eshop_sliders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('link', models.CharField(max_length=200, verbose_name='لینک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_sliders.models.upload_image_path, verbose_name='تصویر')),
            ],
        ),
    ]
